---
title: "Guy Frederick Sutton"
author: Guy Frederick Sutton
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

```{css, echo=FALSE}
# Custom CSS to format sections 
.location{
  display: none;
}
#aside2 > h1 {
display: none;
}
#aside2{
  padding: 0 0 0.6in 0.2in;
  font-size: 0.8rem;
  height: var(--content-area-height);
}
.aside2{
  width: var(--sidebar-width);
  font-size: 0.8rem;
  float: right;
  position: absolute;
  right: 0;
}
/* sidebar */
.aside2 li::before {
  content: none;
}  
  
#skills2 > h2{
  margin: 0.05in 0 0.15in;
  font-weight: 100;
  font-size: 1.1rem;
}
.aside2 .level2{
  margin-top: 0.5in;
}
#skills2{
  line-height: 1.5;
}
#skills2 ul{
  margin: 0.05in 0 0.15in;
  padding: 0 10px 0 10px;
}
```



Aside
================================================================================

Personal Details {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> g.sutton@ru.ac.za
- <i class="fa fa-github"></i> [github.com/guysutton](https://github.com/guysutton)
<!-- - <i class="fa fa-twitter"></i> [twitter.com/Guy_F_Sutton](https://twitter.com/Guy_F_Sutton) -->
- <i class="fas fa-rss"></i> [Statistics Blog](https://statsforscaredecologists.netlify.app/)
- <i class="fas fa-phone"></i> +27 82 552 4643




<i class="fa fa-code"></i> Programming {#skills}
--------------------------------------------------------------------------------

- R / tidyverse
- Julia
- git / GitHub

<i class="fas fa-chart-pie"></i> Data analysis {#skills}
--------------------------------------------------------------------------------

- Linear models (inc. GLM, GLMM)
- Non-linear models (e.g. GAM)
- Data visualisation (e.g. ggplot2)
- Multivariate analyses (e.g. MDS, PCA, multivariate GLM)
- Bayesian regression (INLA, MCMC, Turing)
- Spatial and spatio-temporal modelling (e.g. R-INLA)
- Occupancy and mixture models
- Simulation

<i class="fas fa-book-open"></i> Literate Coding {#skills}
--------------------------------------------------------------------------------

- R markdown / markup
- blogdown / bookdown / pagedown
- xaringan
- distill
- Continuous integration (e.g. Github actions)
- Package development (in R and Julia)
- Functional programming
- Mermaid.js 

Main
================================================================================

Guy Frederick Sutton {#title}
--------------------------------------------------------------------------------

I am a data scientist, an academic, an R and Julia software developer, and an Entomologist. As a data scientist, I build software tools, and develop courses and workshops to teach statistical methods for scientific research, and how to code in R and Julia. My teaching resources are communicated across multiple platforms, including post-graduate courses, professional workshops and my blog: [Stats for Scared Ecologists](https://statsforscaredecologists.netlify.app/). My scientific work focuses on understanding plant-insect interactions and how this knowledge can be used to manage natural ecosystems. 

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Ph.D. in Entomology

Rhodes University

Makhanda, South Africa

2020 - 2017

Professional Experience {data-icon=suitcase data-concise=true}
--------------------------------------------------------------------------------

### Quantitative Ecologist

Rhodes University 

Durban, South Africa

Current - 2019

::: concise
- Project and team management
- Design, conduct, and analyse scientific experiments
- Organise and conduct remote field surveys 
- Communicate results in reports, peer-reviewed papers, and talks
- Develop teaching materials and research software
- Teach technical classes to under-graduates, post-graduates and other researchers 
- Successfully write grant proposals for funding
- Recruit, supervise, and lead a team of MSc and PhD candidates 
:::


Peer-Reviewed Papers {data-icon=file}
--------------------------------------------------------------------------------


### 14 scientific papers, ~73 citations, h-index: 7

<i class="fas fa-link"></i> [More details about my scientific research](https://scholar.google.com/citations?user=vV1bAk0AAAAJ&hl=en)</span>

&nbsp;    
&nbsp;

### [SPEDE-sampler: an R Shiny application to assess how methodological choices and taxon-sampling can affect Generalised Mixed Yule Coalescent (GMYC) output and interpretation](https://onlinelibrary.wiley.com/doi/abs/10.1111/1755-0998.13591)

Molecular Ecology Resources **In Press, 20/01/2021**

N/A

2022

van Steenderen, C.V.S., & **Sutton, G.F.**


### [The alien plants that threaten South Africa's mountain ecosystems](https://www.mdpi.com/2073-445X/10/12/1393)

*Land* 10: e1393

N/A

2021

Canavan, K., Canavan, S., Clark, V.R., Gwate, O., Richardson, D.M., **Sutton, G.F.**, & Martin, G.D.


### [Progress and prospects for the biological control of invasive alien grasses (Poaceae) in South Africa](https://bioone.org/journals/african-entomology/volume-29/issue-3/003.029.0837/Progress-and-Prospects-for-the-Biological-Control-of-Invasive-Alien/10.4001/003.029.0837.short)

*African Entomology* 29: 837-858.

N/A

2021

**Sutton, G.F.**, Bownes, A., Visser, V., Mapaura, A., & Canavan, K. 


### [Biological control of South African plants that are invasive elsewhere in the world](https://bioone.org/journals/african-entomology/volume-29/issue-3/003.029.1005/Biological-Control-of-South-African-Plants-that-are-Invasive-Elsewhere/10.4001/003.029.1005.short)

*African Entomology* 29: 1005-1029

N/A

2021

Olckers, T., Coetzee, J.A., Egli, D., Martin, G.D., Paterson, I.D., **Sutton, G.F.**, & Wood, A.R. 


### [Prioritisation of targets for weed biological control III: A tool to identify the next targets for biological control in South Africa and set priorities for resource allocation](https://www.tandfonline.com/doi/abs/10.1080/09583157.2021.1918638)

*Biocontrol Science and Technology* 31: 584-601

N/A

2021

Canavan, K., Hill, M.P., Ivey, P., **Sutton, G.F.**, Paterson, I.D.


### [Reduction of grazing index in high elevation grasslands following  Black locust  invasion in  South Africa](https://www.sciencedirect.com/science/article/abs/pii/S1550742421000221)

*Rangeland Ecology and Management* 76: 109-117

N/A

2021

Chikowore, G., Mutamiswa, R., Martin, G.D., **Sutton, G.F.**, & Chidawanyika, F.


### [Field-based ecological studies to assess prospective biological control agents for invasive alien plants: An example from giant rat's tail grass](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1365-2664.13834)

*Journal of Applied Ecology* 58: 1043-1054

N/A

2021

**Sutton, G.F.**, Canavan, K., Day, M.D., & Paterson, I.D. 


### [Climate modelling suggests a review of the legal status of Brazilian pepper *Schinus terebinthifolia* in South Africa is required](https://https://www.sciencedirect.com/science/article/abs/pii/S025462992030123X)

*South African Journal of Botany* 132: 95-102

N/A

2020

Martin, G.D., Magengelele, N.L., Paterson, I.D., **Sutton, G.F.**


### [Grasses as suitable targets for classical weed  biological control](https://link.springer.com/article/10.1007/s10526-019-09968-8)

*BioControl* 64: 605-622

N/A

2019

**Sutton, G.F.**, Canavan, K., Day, M.D., Den Breeyen, A., Cristofaro, M., McConnachie, A., Goolsby, J.A., & Paterson, I.D.


### [Searching for a needle in a haystack: where to survey for climatically-matched biological control agents for two grasses (*Sporobolus* spp.) invading Australia](https://www.sciencedirect.com/science/article/pii/S1049964418306480)

*Biological Control* 129: 37-44

N/A

2019

**Sutton, G.F.**


### [Evaluating the efficacy of *Hypogeococcus* sp. as a biological control agent of the cactaceous weed *Cereus jamacaru* in South Africa](https://link.springer.com/article/10.1007/s10526-018-9887-3)

*BioControl* 63: 493-503

N/A

2018

**Sutton, G.F.**, Klein, H., & Paterson, I.D.


### [Genetic matching of invasive populations of the African tulip tree, *Spathodea campanulata* Beauv. (Bignoniaceae), to their native distribution: maximising the likelihood of selecting host-compatible biological control agents](https://www.sciencedirect.com/science/article/pii/S1049964417301810)

*Biological Control* 114: 167-175

N/A

2017

**Sutton, G.F.**, Paterson, I.D., & Paynter, Q.


### [Predicting the risk of non-target damage to a close relative of a target weed using sequential no- choice tests, paired-choice tests and olfactory discrimination experiments](https://www.tandfonline.com/doi/abs/10.1080/09583157.2017.1291907)

*Biocontrol Science and Technology* 27: 364-377

N/A

2017

**Sutton, G.F.**, Paterson, I.D., Compton, S.G., & Paynter, Q.


### [Naturally occurring phytopathogens enhance biological control of water hyacinth (*Eichhornia crassipes*) by *Megamelus scutellaris* (Hemiptera: Delphacidae), even in eutrophic water](https://www.sciencedirect.com/science/article/pii/S1049964416301840)

*Biological Control* 103: 261-268

N/A

2016

**Sutton, G.F.**, Compton, S.G., & Coetzee, J.A.

<!--------------- END OF PAGE 1 ---------------------------->


Software Development {data-icon=newspaper}
--------------------------------------------------------------------------------

### [R Package: *ThermalSampleR*](https://github.com/clarkevansteenderen/ThermalSampleR)

N/A

N/A

Current - 2019

- *ThermalSampleR* is an R package I co-wrote and maintain that performs a range of simulations to aid sample size planning for experiments determining physiological limits (e.g. CT~min~/CT~max~) of biological organisms.

### [R Package: *sapiaR*](https://github.com/guysutton/sapia_type_maps)

N/A

N/A

Current - 2019

- *sapiaR* is a developmental R package I wrote and maintain that automates the calculation of geospatial statistics and plotting of the characteristic South African Plant Invaders Atlas (SAPIA)-style distribution maps used in numerous publications on invasive plants in South Africa.

### [Julia Package: *ModelCheck.jl*](https://github.com/guysutton/ModelCheck.jl)

N/A

N/A

Current - 2020

- *ModelCheck.jl* is a developmental Julia package I wrote and maintain that allows users to perform model diagnostics on their fitted statistical models, by producing a range of residual diagnostics plots (e.g. quantile-quantile plots, fitted versus residuals plots).

Teaching {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### [Introduction to R for biologists](https://github.com/guysutton/intro_r_biologists)

N/A

N/A

Current - 2019

- As co-instructor, I developed a series of lectures for this Honours-level course on linear modelling in R. These lectures introduce students to common statistical analyses used in the field of ecology, including: linear regression, ANOVA, ANCOVA and more complex linear models (e.g. binomial GLM, poisson GLM), and demonstrate how to code these analyses in R, including: model diagnostics and evaluation, inference and producing publication-quality written summaries and visualisations.

### [R workshops](https://github.com/guysutton/2021_CRI_GLM_workshop)

N/A

N/A

Current - 2019

- I have developed a number of weekly 1 - 1.5 hour and multi-day statistics workshops, primarily using the R statistical software, to graduate students, faculty and industry partners. These workshops are driven by the needs of the attendees, covering topics including: data management/curation, data cleaning, linear modelling, multivariate analyses, data visualisation and spatial analyses (e.g. mapping).


Conference Proceedings {data-icon=newspaper}
--------------------------------------------------------------------------------

### A weed biocontrol program for the Cook Islands: progress report

*Proceedings of the XV International Symposium on the Biological Control of Weeds*

N/A

2018

Paynter, Q., Poeschko, M., Mitchell, C., Probst, C., Barreto, R.W., 
Colman, A.A., Macedo, D., Dodd, S., Johnson, T., McCormack, G., Paterson, I.D.,
**Sutton, G.F.**, & Winks, C.J.


Conference Presentations {data-icon=newspaper}
--------------------------------------------------------------------------------

### South Africa is a hotspot for previously unknown stem-boring wasps of grasses (*Tetramesa*; Eurytomidae)

*56th Annual Congress of the Grassland Society of Southern Africa*

N/A

2021

**Sutton, G.F.**, van Steenderen, C., Canavan, K., Yell, L., & Paterson, I.D.


### Anthropogenic disturbance reduces the prevalence and abundance of specialist, but not generalist, grass-associated insects across South Africa: implications for biological control

*22nd Congress of the Entomological Society of Southern Africa*

N/A

2021

**Sutton, G.F.**, Canavan, K., & Paterson, I.D.


### Invasive grasses as suitable biological control targets: a South African perspective

*46th South African Association of Botanists Annual Conference*

N/A

2020

**Sutton, G.F.**, Canavan, K., Visser, V., & Paterson, I.D.


### Are grasses suitable targets for biological control?: a case-study of two African grasses (*Sporobolus* spp.) invading Australia

*46th National Symposium on Biological Invasions in southern Africa*

N/A

2019

**Sutton, G.F.**, Canavan, K., & Paterson, I.D.


### Invasive grasses and classical weed biological control: are we missing a trick?

*Invasive Grass Working Group Meeting*

N/A

2018

**Sutton, G.F.**, Chari, L., & Canavan, K.


### Prospects for the biological control of invasive rat's tail grasses (*Sporobolus* spp.) in Australia

*XV International Symposium on the Biological Control of Weeds*

N/A

2018

**Sutton, G.F.**, Day, M.D., Canavan, K., & Paterson, I.D.


### Are invasive grasses good targets for biological control?: A case study of two African *Sporobolus* spp. invading Australia

*52nd Annual Congress of the Grassland Society of Southern Africa*

N/A

2017

**Sutton, G.F.**, Canavan, K., & Paterson, I.D.


### Does *Hypogeococcus festerianus* (Hemiptera: Pseudococcidae) successfully control the cactaceous weed *Cereus jamacaru* in South Africa?

*44th National Symposium on Biological Invasions in southern Africa*

N/A

2017

**Sutton, G.F.**, Klein, H., & Paterson, I.D.


### Potential biological control agents for *Spathodea campanulata* (Bignoniaceae)

*XIX Congress of the Entomological Society of Southern Africa*

N/A

2015

Paterson, I.D., Paynter, Q., **Sutton, G.F.**, & Mpekula, O.


### Determination of the origin of two invasive populations of African Tulip Tree using ISSR and AFLP molecular markers

*XIX Congress of the Entomological Society of Southern Africa*

N/A

2015

**Sutton, G.F.**, Timm, A.E., & Paterson, I.D.


Community Engagement {data-icon=newspaper}
--------------------------------------------------------------------------------

## (1) Public Seminars

### Invasive alien species in urban gardens - regulations and management.

*Port Alfred Gardeners Society*

N/A

2021

**Sutton, G.F.**

## (2) OUTREACH

### Student Mentor

*Entomological Society of Southern Africa Student Outreach Programme*

N/A

2019 - 2015

- Assisted in laboratory set-up, specimen collection and preservation, and practical demonstrations of several aspects of entomology to local school groups


### Student Assistant

*WILDreach Society, Rhodes University*

N/A

2016 - 2015

- Aided in specimen collection, curation and preservation techniques, and practical demonstrations and explanations of general aspects of entomology and undergraduate biology to local school groups  

Professional Service {data-icon=newspaper}
--------------------------------------------------------------------------------

## (1) Peer review

### I have served as an expert reviewer for:

N/A

N/A

:::concise
- Biological Invasions (3 papers) 
- Austral Ecology (2 papers)
- Biological Control (1 paper)
- BioControl (1 paper) 
- Biocontrol Science and Technology (1 paper)
- Plant Ecology (1 paper) 
- Arthropod-Plant Interactions (1 paper)
- The Rangeland Journal (1 paper)
- South African Journal of Botany (1 paper)
- Environmental Monitoring and Assessment (1 paper)
- Management of Biological Invasions (1 paper)
- Assorted book chapters 
:::


## (2) Professional groups

### Invited member of the scientific committee 

*45th National Symposium on Biological Invasions*

N/A

2021

- Screened abstracts and provided recommendations to the conference organisers on how to develop the scientific programme. 


### Alien Grass Working Group of South Africa

*Committee member*

N/A

2021 - 2017

- This is a professional working group that directly advises government on policies and practices for the management of invasive alien grasses in Southern Africa, including risk assessment and recommendations for listing and regulating new invasive grass species in South Africa






Aside2
================================================================================

&nbsp; &nbsp; <i class="fa fa-cube"></i> References {#skills2}
--------------------------------------------------------------------------------

- &nbsp; &nbsp; &nbsp; Professor Iain Paterson 
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fa fa-map-marker"></i> Rhodes University
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fas fa-envelope"></i> [I.paterson@ru.ac.za](I.paterson@ru.ac.za)
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fas fa-phone"></i> +27 46 603 8098
- &nbsp;
- &nbsp; &nbsp; &nbsp; Distinguished Professor Martin Hill 
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fa fa-map-marker"></i> Rhodes University
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fas fa-envelope"></i> [M.hill@ru.ac.za](M.hill@ru.ac.za)
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fas fa-phone"></i> +27 46 603 8712
- &nbsp;
- &nbsp; &nbsp; &nbsp; Mr Michael Day 
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fa fa-map-marker"></i> Queensland Department  
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; of Agriculture and Fisheries,
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Australia
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fas fa-envelope"></i> [Michael.Day@daf.qld.gov.au](Michael.Day@daf.qld.gov.au)
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fas fa-phone"></i> +61 407 128 278
- &nbsp;
- &nbsp; &nbsp; &nbsp; Dr Kim Canavan
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fa fa-map-marker"></i> Rhodes University
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fas fa-envelope"></i> [K.canavan@ru.ac.za](K.canavan@ru.ac.za)
- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <i class="fas fa-phone"></i> +27 72 633 3073
- &nbsp;

<br><br>

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Resume generated in `R` and [pagedown](https://github.com/rstudio/pagedown)

Last updated: `r gsub(" +", " ", format(Sys.Date(), "%B %e, %Y"))`


</div>